name: using with arg
run-name: using the with arguments

on:
  push:
    branches:
      - main
      - features

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code 
        uses: actions/checkout@v2
        with:
          repository: apache/tomcat
          ref: master
          path: ./tomcat

      - name: Set up java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
